### ISSUE TITLE
Поддержка IPOE

### ISSUE THREAD

**Issue by hakerillo66** [svlobanov/accel-web-manager#1]
Добрый день. 

На версии accel-web-manager_0.3.0-1_all не отображает ipoe интерфейсы. Этот функционал не поддерживается?

**Comment by hakerillo66** [comment]
br1: header not found (< 2 lines)

**Comment by svlobanov** [comment]
it should work for ipoe interfaces. looks like some environment problem

Please provide some more info:
1. OS distro name (cat /etc/issue, lsb_release -a)
2. accel-cmd version (`accel-cmd --version`)
3. which accel-cmd
4. sudo systemctl status accel-web-manager

**Comment by hakerillo66** [comment]
```
root@nas3:~# cat /etc/issue
Debian GNU/Linux 11

```

```
root@nas3:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

```
root@nas3:~# accel-cmd -V
accel-cmd 1.12.0-192-g61ba3af

```
```
root@nas3:~# which accel-cmd
/usr/bin/accel-cmd

```

![Screenshot_1](https://user-images.githubusercontent.com/16403928/187178622-f4740b68-88e9-45dc-92ad-7c4850cde33f.png)

**Comment by svlobanov** [comment]
Please execute the command: 'accel-cmd show sessions sid,ifname,username,state,uptime-raw,ip,ip6,ip6-dp,calling-sid,called-sid,comp,rate-limit,type,rx-bytes-raw,tx-bytes-raw,rx-pkts,tx-pkts'

Most probably, some columns are absent. In this case you will get the error like this `unknown column rate-limit`

To fix the issue, please comment rate-limit in /var/lib/accel-web-manager/backend/column_settings.py:
```
root@deb11:/var/lib/accel-web-manager/backend# git diff
diff --git a/column_settings.py b/column_settings.py
index df470be..03d84ee 100644
--- a/column_settings.py
+++ b/column_settings.py
@@ -84,13 +84,13 @@ session_columns = {
         "type": "string",
         "operator": "contains",
     },
-    "rate-limit": {
-        "name": "rl",
-        "header": "Rate-Limit",
-        "type": "string",
-        "operator": "contains",
-        "sort": "rate",
-    },
+#    "rate-limit": {
+#        "name": "rl",
+#        "header": "Rate-Limit",
+#        "type": "string",
+#        "operator": "contains",
+#        "sort": "rate",
+#    },
     "type": {
         "name": "ty",
         "header": "Type",
```

then restart accel-web-manager backend: `systemctl restart accel-web-manager`

**Comment by hakerillo66** [comment]
Спасибо, это решило проблему. Список сессий появился
