### ISSUE TITLE
Bras authorization

### ISSUE THREAD

**Issue by SmartHome2021** [svlobanov/accel-web-manager#2]
I apologize for the stupid question, but I do not understand the mechanism of authorization of the service on the accel server.
in the configuration file ../bras_settings, I changed the ip to the address of my server, but no miracle happened. 
the error "no such file or directory" is hanging in the web.

upd. the problem occurs only when trying to connect to a remote bras, everything works correctly locally.

**Comment by svlobanov** [comment]
Try this config:
```
# Please do not use special name 'all' for BRAS
bras_options = {
    "br1": ["accel-cmd", "-Hlocalhost", "-p2001"],
    "br2": ["accel-cmd", "-H192.0.2.0", "-p2001", "-PYOUR_PASSWORD"],
}
```

**Comment by SmartHome2021** [comment]
> Try this config:

Does not work. 
Maybe we didn't understand each other. 
I will try to explain the concept. 
There is a conditional server with accel installed, when connecting via ssh to the server, we get the opportunity to control accel by calling **accel-cmd**, and everything works because **accel-cmd** interprets our commands into a byte code understandable accel. 
In the case of a remote connection, we knock directly on accel itself bypassing the server and there is no interpretation of commands, accel is waiting for a set of bytes, and receives a utf8 string. 
It is easy to verify this if you connect via telnet to the 2001 port and try to enter a command, nothing will happen, because there is no layer. Accordingly, I can't figure out how to run it remotely.
Thank you in advance

**Comment by svlobanov** [comment]
Does 'accel-cmd -Hremote_bras' work from the server with accel-web-manager installed? if it works, then, accel-web-manager should work. accel-web-manager connects to remote bras from backend (from python code) using accel-cmd application. It doesn't connect to bras directly from the UI js code.
Which error do you have when you try add remote bras to accel-web-manager config?

**Comment by SmartHome2021** [comment]
> Does 'accel-cmd -Hremote_bras' work from the server with accel-web-manager installed? if it works, then, accel-web-manager should work. accel-web-manager connects to remote bras from backend (from python code) using accel-cmd application. It doesn't connect to bras directly from the UI js code. Which error do you have when you try add remote bras to accel-web-manager config?

I understand how and where the code is executed :)
The answer to your question is that the "accel-cmd -Hremote_bras" commands do not work from my computer with the accel-web-manager utility installed.
The question is different. The utility works fine on a bras server with accel-ppp installed, because it has the ability to call accel-cmd.
I am considering a situation where we have bras remotely, and your utility is installed, for example, on my personal PC.
It turns out that in order for this to work, I have to deploy accel-ppp on my PC

**Comment by svlobanov** [comment]
In your case, you have to copy accel-cmd binary to the host where accel-web-manager is installed. If OS is very different, then compile accel-cmd on the host where accel-web-manager is installed. 

You can easily compile accel-cmd (even on non-linux OS):
```
git clone https://github.com/accel-ppp/accel-ppp
cd accel-ppp/accel-cmd
cc -DACCEL_PPP_VERSION="\"1\"" -o accel-cmd accel_cmd.c
```

Please copy accel-cmd to "system" path that is visible by backend or add a full path to accel-cmd to bras_settings.py

**Comment by SmartHome2021** [comment]
> In your case, you have to copy accel-cmd binary to the host where accel-web-manager is installed. If OS is very different, then compile accel-cmd on the host where accel-web-manager is installed.

I did exactly that and everything works great. Thanks for the help !

**Comment by svlobanov** [comment]
good to know
